import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { CheckoutProvider } from "./context/CheckoutContext";
import LayoutWrapper from "./components/LayoutWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Toaster />
        <Providers>
          <TooltipProvider>
            <CheckoutProvider>
              <LayoutWrapper>{children}</LayoutWrapper>
            </CheckoutProvider>
          </TooltipProvider>
        </Providers>
      </body>
    </html>
  );
}

